CREATE TABLE [activity].[RaceResultImport] (
    [Id]               INT            IDENTITY (1, 1) NOT NULL,
    [RaceDefinition]   NVARCHAR (100) NOT NULL,
    [RaceType]         NVARCHAR (100) NOT NULL,
    [Discpline]        NVARCHAR (100) NOT NULL,
    [Province]         NVARCHAR (100) NOT NULL,
    [FinYear]          INT            NOT NULL,
    [EventDate]        DATETIME2 (7)  NOT NULL,
    [Distance]         NVARCHAR (4)   NOT NULL,
    [AgeGroup]         NVARCHAR (100) NOT NULL,
    [Organisation]     NVARCHAR (100) NOT NULL,
    [Position]         INT            NOT NULL,
    [TimeTaken]        TIME (7)       NOT NULL,
    [FirstName]        NVARCHAR (100) NOT NULL,
    [Surname]          NVARCHAR (100) NOT NULL,
    [Discriminator]    INT            NOT NULL,
    [PersonId]         INT            NULL,
    [RaceDistanceId]   INT            NULL,
    [CreatedUserId]    NVARCHAR (450) NOT NULL,
    [UpdatedUserId]    NVARCHAR (450) NULL,
    [CreatedTimestamp] DATETIME2 (7)  DEFAULT (getdate()) NOT NULL,
    [UpdatedTimestamp] DATETIME2 (7)  NULL,
    [IsActive]         BIT            DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_activity.RaceResultImport] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_activity.RaceResultImport_dbo_Person] FOREIGN KEY ([PersonId]) REFERENCES [dbo].[Person] ([Id]),
    CONSTRAINT [FK_activity.RaceResultImport_RaceDistance] FOREIGN KEY ([PersonId]) REFERENCES [dbo].[Person] ([Id]),
    CONSTRAINT [FK_activity.RaceResultImport_RaceDistance_Id] FOREIGN KEY ([RaceDistanceId]) REFERENCES [activity].[RaceDistance] ([Id]),
    CONSTRAINT [FK_activity.RaceResultImport_Security.User_Created] FOREIGN KEY ([CreatedUserId]) REFERENCES [dbo].[AspNetUsers] ([Id]),
    CONSTRAINT [FK_activity.RaceResultImportt_Security.User_Updated] FOREIGN KEY ([UpdatedUserId]) REFERENCES [dbo].[AspNetUsers] ([Id]),
    CONSTRAINT [UQ_activity.RaceResultImport] UNIQUE NONCLUSTERED ([Discriminator] ASC)
);

