CREATE TYPE [worker].[ut_RemittanceStaging] AS TABLE (
    [Id]                    INT             NULL,
    [RemittanceSummaryId]   INT             NOT NULL,
    [FirstName]             NVARCHAR (MAX)  NOT NULL,
    [OtherName]             NVARCHAR (MAX)  NULL,
    [Surname]               NVARCHAR (MAX)  NOT NULL,
    [Initials]              NVARCHAR (MAX)  NULL,
    [EmploymentDate]        DATETIME        NOT NULL,
    [TerminationDate]       DATETIME        NULL,
    [EmploymentNumber]      NVARCHAR (MAX)  NULL,
    [IDNumber]              NVARCHAR (MAX)  NOT NULL,
    [Cell]                  NVARCHAR (MAX)  NULL,
    [Branch]                NVARCHAR (MAX)  NOT NULL,
    [EmploymentStatus]      NVARCHAR (MAX)  NOT NULL,
    [StatusDate]            NVARCHAR (MAX)  NOT NULL,
    [Ethnic]                NVARCHAR (MAX)  NULL,
    [EmploymentPosition]    NVARCHAR (MAX)  NOT NULL,
    [BirthDate]             DATETIME        NULL,
    [Sex]                   NVARCHAR (MAX)  NOT NULL,
    [Amount]                DECIMAL (18, 2) NOT NULL,
    [ValidationErrorTypeId] INT             NULL,
    [RowNumber]             INT             NOT NULL,
    [IsActive]              BIT             DEFAULT ((1)) NOT NULL,
    [CreatedTimestamp]      DATETIME2 (7)   DEFAULT (getdate()) NOT NULL,
    [UpdatedTimestamp]      DATETIME2 (7)   NULL,
    [CreatedUserId]         NVARCHAR (450)  NOT NULL,
    [UpdatedUserId]         NVARCHAR (450)  NULL);

