CREATE TABLE [worker].[MemberStaging] (
    [Id]                   INT            IDENTITY (1, 1) NOT NULL,
    [FirstName]            NVARCHAR (250) NOT NULL,
    [Surname]              NVARCHAR (250) NOT NULL,
    [Initials]             NVARCHAR (250) NULL,
    [OtherName]            NVARCHAR (250) NULL,
    [IDNumber]             NVARCHAR (13)  NULL,
    [ContactNo]            NVARCHAR (10)  NOT NULL,
    [Email]                NVARCHAR (100) NOT NULL,
    [BirthDate]            DATETIME       NOT NULL,
    [EmmergencyContact1]   NVARCHAR (250) NOT NULL,
    [EmmergencyContactNo1] NVARCHAR (250) NOT NULL,
    [EmmergencyContact2]   NVARCHAR (250) NOT NULL,
    [EmmergencyContactNo2] NVARCHAR (250) NOT NULL,
    [Occupation]           NVARCHAR (250) NULL,
    [Company]              NVARCHAR (250) NULL,
    [WorkTelephone]        NVARCHAR (250) NULL,
    [HomeTelephone]        NVARCHAR (250) NULL,
    [PrevYearLicence]      NVARCHAR (10)  NULL,
    [CurrentYearLicence]   NVARCHAR (10)  NULL,
    [MedicalAidName]       NVARCHAR (100) NULL,
    [MedicalAidNumber]     NVARCHAR (100) NULL,
    [TitleId]              INT            NULL,
    [GenderId]             INT            NOT NULL,
    [IDTypeId]             INT            NOT NULL,
    [CountryId]            INT            NOT NULL,
    [AddressId]            INT            NOT NULL,
    [IsFromFront]          BIT            NOT NULL,
    [IsFinalised]          BIT            NOT NULL,
    [IsRejected]           BIT            NOT NULL,
    [Comment]              NVARCHAR (500) NULL,
    [IsActive]             BIT            DEFAULT ((1)) NOT NULL,
    [CreatedTimestamp]     DATETIME2 (7)  DEFAULT (getdate()) NOT NULL,
    [UpdatedTimestamp]     DATETIME2 (7)  NULL,
    [CreatedUserId]        NVARCHAR (450) NOT NULL,
    [UpdatedUserId]        NVARCHAR (450) NULL,
    CONSTRAINT [PK_MemberStaging] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_MemberStaging_Address_Id] FOREIGN KEY ([AddressId]) REFERENCES [dbo].[Address] ([Id]),
    CONSTRAINT [FK_MemberStaging_AspNetUsers_CreatedUserId] FOREIGN KEY ([CreatedUserId]) REFERENCES [dbo].[AspNetUsers] ([Id]),
    CONSTRAINT [FK_MemberStaging_AspNetUsers_UpdatedUserId] FOREIGN KEY ([UpdatedUserId]) REFERENCES [dbo].[AspNetUsers] ([Id]),
    CONSTRAINT [FK_MemberStaging_Country_Id] FOREIGN KEY ([CountryId]) REFERENCES [gis].[Country] ([Id]),
    CONSTRAINT [FK_MemberStaging_Gender_Id] FOREIGN KEY ([GenderId]) REFERENCES [meta].[Gender] ([Id]),
    CONSTRAINT [FK_MemberStaging_IDType_Id] FOREIGN KEY ([IDTypeId]) REFERENCES [meta].[IDType] ([Id]),
    CONSTRAINT [FK_MemberStaging_Title_Id] FOREIGN KEY ([TitleId]) REFERENCES [meta].[Title] ([Id])
);

